# Generated by Django 4.2.6 on 2023-10-10 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='appeal',
            name='app_status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'On Moderation'), (3, 'Posted'), (4, 'Assigned'), (5, 'Completed'), (6, 'Waiting For Approve'), (7, 'Deleted')], default=1, verbose_name='Appeal status'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appeals_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='appeals.category'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_appeals_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
